In [1]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle

# Carregando dataset UNSW completo pre-processamento MINIMO

In [2]:
df_unsw_full = pd.read_csv('/media/kelson/Maxtor/Trabalho/doutorado/artigo_preprocessamento/artigo/dataset_unsw/df_unsw_full.csv', low_memory=False)

In [3]:
df_unsw_full

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,1390,53,udp,CON,0.001055,132,164,31,29,0,...,0,3,7,1,3,1,1,1,Benign,0
1,33661,1024,udp,CON,0.036133,528,304,31,29,0,...,0,2,4,2,3,1,1,2,Benign,0
2,1464,53,udp,CON,0.001119,146,178,31,29,0,...,0,12,8,1,2,2,1,1,Benign,0
3,3593,53,udp,CON,0.001209,132,164,31,29,0,...,0,6,9,1,1,1,1,1,Benign,0
4,49664,53,udp,CON,0.001169,146,178,31,29,0,...,0,7,9,1,1,1,1,1,Benign,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2540039,33094,43433,tcp,FIN,0.087306,320,1828,31,29,1,...,7,1,2,3,3,1,1,3,Benign,0
2540040,20848,21,tcp,CON,0.365058,456,346,31,29,2,...,2,2,2,2,2,2,2,2,Benign,0
2540041,21511,21,tcp,CON,6.335154,1802,2088,31,29,7,...,2,2,2,4,2,2,2,2,Benign,0
2540042,35433,80,tcp,CON,2.200934,3498,166054,31,29,2,...,7,1,1,2,4,2,2,2,Benign,0
2540043,17293,110,tcp,CON,0.942984,574,676,62,252,5,...,7,1,1,2,4,2,2,2,Exploits,1

In [4]:
# visualizando os valores nulos
df_unsw_full.isnull().sum()

sport               0
dsport              0
proto               0
state               0
dur                 0
sbytes              0
dbytes              0
sttl                0
dttl                0
sloss               0
dloss               0
service             0
Sload               0
Dload               0
Spkts               0
Dpkts               0
swin                0
dwin                0
stcpb               0
dtcpb               0
smeansz             0
dmeansz             0
trans_depth         0
res_bdy_len         0
Sjit                0
Djit                0
Stime               0
Ltime               0
Sintpkt             0
Dintpkt             0
tcprtt              0
synack              0
ackdat              0
is_sm_ips_ports     0
ct_state_ttl        0
ct_flw_http_mthd    0
is_ftp_login        0
ct_ftp_cmd          0
ct_srv_src          0
ct_srv_dst          0
ct_dst_ltm          0
ct_src__ltm         0
ct_src_dport_ltm    0
ct_dst_sport_ltm    0
ct_dst_src_ltm      0
attack_cat          0
Label               0
dtype: int64

In [5]:
# verifica detalhes das variáveis
# variáveis nominais: #proto #state #service #ct_ftp_cmd
#df_unsw_full.shape
#df_unsw_full.describe()
#df_unsw_full.dtypes
#df_unsw_full.ct_ftp_cmd.value_counts()
#np.unique(df_unsw_full['sport'])
#len(np.unique(df_unsw_full.ct_ftp_cmd))
pd.set_option('display.max_rows', None)
print(df_unsw_full.attack_cat.value_counts())
pd.set_option('display.max_rows', False)

Benign            2218761
Generic            215481
Exploits            44525
Fuzzers             24246
DoS                 16353
Reconnaissance      13987
Analysis             2677
Backdoor             2329
Shellcode            1511
Worms                 174
Name: attack_cat, dtype: int64

# Pré-processamento com Condificação (LabelEncoder)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
pd.set_option('display.max_rows', None)
print(df_unsw_full.dtypes)
pd.set_option('display.max_rows', False)

sport                object
dsport               object
proto                object
state                object
dur                 float64
sbytes                int64
dbytes                int64
sttl                  int64
dttl                  int64
sloss                 int64
dloss                 int64
service              object
Sload               float64
Dload               float64
Spkts                 int64
Dpkts                 int64
swin                  int64
dwin                  int64
stcpb                 int64
dtcpb                 int64
smeansz               int64
dmeansz               int64
trans_depth           int64
res_bdy_len           int64
Sjit                float64
Djit                float64
Stime                 int64
Ltime                 int64
Sintpkt             float64
Dintpkt             float64
tcprtt              float64
synack              float64
ackdat              float64
is_sm_ips_ports       int64
ct_state_ttl          int64
ct_flw_http_mthd    float64
is_ftp_login        float64
ct_ftp_cmd            int64
ct_srv_src            int64
ct_srv_dst            int64
ct_dst_ltm            int64
ct_src__ltm           int64
ct_src_dport_ltm      int64
ct_dst_sport_ltm      int64
ct_dst_src_ltm        int64
attack_cat           object
Label                 int64
dtype: object

In [9]:
df_unsw_full.head()

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,1390,53,udp,CON,0.001055,132,164,31,29,0,...,0,3,7,1,3,1,1,1,Benign,0
1,33661,1024,udp,CON,0.036133,528,304,31,29,0,...,0,2,4,2,3,1,1,2,Benign,0
2,1464,53,udp,CON,0.001119,146,178,31,29,0,...,0,12,8,1,2,2,1,1,Benign,0
3,3593,53,udp,CON,0.001209,132,164,31,29,0,...,0,6,9,1,1,1,1,1,Benign,0
4,49664,53,udp,CON,0.001169,146,178,31,29,0,...,0,7,9,1,1,1,1,1,Benign,0

In [10]:
# cria variáveis recebendo a função LabelEncoder
label_encoder_sport  = LabelEncoder()
label_encoder_dsport = LabelEncoder()
label_encoder_proto  = LabelEncoder()
label_encoder_state = LabelEncoder()
label_encoder_service = LabelEncoder()

In [12]:
# faz a codificação das variáveis nominais (colunas) específicas
#srcip #sport #dstip #dsport #proto #state #service
df_unsw_full['sport'] = label_encoder_proto.fit_transform(df_unsw_full['sport'])
df_unsw_full['dsport'] = label_encoder_proto.fit_transform(df_unsw_full['dsport'])
df_unsw_full['proto'] = label_encoder_proto.fit_transform(df_unsw_full['proto'])
df_unsw_full['state'] = label_encoder_state.fit_transform(df_unsw_full['state'])
df_unsw_full['service'] = label_encoder_service.fit_transform(df_unsw_full['service'])

In [13]:
df_unsw_full.head()

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,4276,47344,120,2,0.001055,132,164,31,29,0,...,0,3,7,1,3,1,1,1,Benign,0
1,26036,253,120,2,0.036133,528,304,31,29,0,...,0,2,4,2,3,1,1,2,Benign,0
2,5091,47344,120,2,0.001119,146,178,31,29,0,...,0,12,8,1,2,2,1,1,Benign,0
3,28534,47344,120,2,0.001209,132,164,31,29,0,...,0,6,9,1,1,1,1,1,Benign,0
4,43654,47344,120,2,0.001169,146,178,31,29,0,...,0,7,9,1,1,1,1,1,Benign,0

In [15]:
pd.set_option('display.max_rows', None)
print(df_unsw_full.dtypes)
pd.set_option('display.max_rows', False)

sport                 int64
dsport                int64
proto                 int64
state                 int64
dur                 float64
sbytes                int64
dbytes                int64
sttl                  int64
dttl                  int64
sloss                 int64
dloss                 int64
service               int64
Sload               float64
Dload               float64
Spkts                 int64
Dpkts                 int64
swin                  int64
dwin                  int64
stcpb                 int64
dtcpb                 int64
smeansz               int64
dmeansz               int64
trans_depth           int64
res_bdy_len           int64
Sjit                float64
Djit                float64
Stime                 int64
Ltime                 int64
Sintpkt             float64
Dintpkt             float64
tcprtt              float64
synack              float64
ackdat              float64
is_sm_ips_ports       int64
ct_state_ttl          int64
ct_flw_http_mthd    float64
is_ftp_login        float64
ct_ftp_cmd            int64
ct_srv_src            int64
ct_srv_dst            int64
ct_dst_ltm            int64
ct_src__ltm           int64
ct_src_dport_ltm      int64
ct_dst_sport_ltm      int64
ct_dst_src_ltm        int64
attack_cat           object
Label                 int64
dtype: object

# Divisão dataset full em Train (50%) e Test - Base-Line (50%)

In [16]:
# separação dos tipos de ataque (coluna attack_cat)
df_benign = df_unsw_full[df_unsw_full.attack_cat == 'Benign']
df_generic = df_unsw_full[df_unsw_full.attack_cat == 'Generic']
df_exploits = df_unsw_full[df_unsw_full.attack_cat == 'Exploits']
df_fuzzers = df_unsw_full[df_unsw_full.attack_cat == 'Fuzzers']
df_dos = df_unsw_full[df_unsw_full.attack_cat == 'DoS']
df_reconnaissance = df_unsw_full[df_unsw_full.attack_cat == 'Reconnaissance']
df_analysis = df_unsw_full[df_unsw_full.attack_cat == 'Analysis']
df_backdoor = df_unsw_full[df_unsw_full.attack_cat == 'Backdoor']
df_shellcode = df_unsw_full[df_unsw_full.attack_cat == 'Shellcode']
df_worms = df_unsw_full[df_unsw_full.attack_cat == 'Worms']

In [17]:
# dimensão do dataframe fragmentado
print(df_benign.shape)
print(df_generic.shape)
print(df_exploits.shape)
print(df_fuzzers.shape)
print(df_dos.shape)
print(df_reconnaissance.shape)
print(df_analysis.shape)
print(df_backdoor.shape)
print(df_shellcode.shape)
print(df_worms.shape)

(2218761, 47)
(215481, 47)
(44525, 47)
(24246, 47)
(16353, 47)
(13987, 47)
(2677, 47)
(2329, 47)
(1511, 47)
(174, 47)

In [18]:
# reseta os índices
df_benign.reset_index(drop=True, inplace=True)
df_generic.reset_index(drop=True, inplace=True)
df_exploits.reset_index(drop=True, inplace=True)
df_fuzzers.reset_index(drop=True, inplace=True)
df_dos.reset_index(drop=True, inplace=True)
df_reconnaissance.reset_index(drop=True, inplace=True)
df_analysis.reset_index(drop=True, inplace=True)
df_backdoor.reset_index(drop=True, inplace=True)
df_shellcode.reset_index(drop=True, inplace=True)
df_worms.reset_index(drop=True, inplace=True)

In [19]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_benign50 = df_benign.iloc[:1109380,:]
df2_benign50 = df_benign.iloc[1109381:,:]

In [20]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_generic50 = df_generic.iloc[:107740,:]
df2_generic50 = df_generic.iloc[107741:,:]

In [21]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_exploits50 = df_exploits.iloc[:22262,:]
df2_exploits50 = df_exploits.iloc[22263:,:]

In [22]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_fuzzers50 = df_fuzzers.iloc[:12122,:]
df2_fuzzers50 = df_fuzzers.iloc[12123:,:]

In [23]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_dos50 = df_dos.iloc[:8176,:]
df2_dos50 = df_dos.iloc[8177:,:]

In [24]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_reconnaissance50 = df_reconnaissance.iloc[:6993,:]
df2_reconnaissance50 = df_reconnaissance.iloc[6994:,:]

In [25]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_analysis50 = df_analysis.iloc[:1338,:]
df2_analysis50 = df_analysis.iloc[1339:,:]

In [26]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_backdoor50 = df_backdoor.iloc[:1164,:]
df2_backdoor50 = df_backdoor.iloc[1165:,:]

In [27]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_shellcode50 = df_shellcode.iloc[:755,:]
df2_shellcode50 = df_shellcode.iloc[756:,:]

In [28]:
# divisão dos dataframe fragmentados por linha (50 a 50)
df1_worms50 = df_worms.iloc[:86,:]
df2_worms50 = df_worms.iloc[87:,:]

In [29]:
# juntando os dataframes train50
df_unsw_train50 = pd.concat([df1_benign50, df1_generic50, df1_exploits50, df1_fuzzers50, df1_dos50, 
                             df1_reconnaissance50, df1_analysis50, df1_backdoor50, df1_shellcode50, df1_worms50])
# embaralha do dataframe 
df_unsw_train50 = shuffle(df_unsw_train50)
# reseta os indices
df_unsw_train50.reset_index(drop=True, inplace=True)
# verifica a dimensão
df_unsw_train50.shape

(1270016, 47)

In [30]:
# juntando os dataframes test50
df_unsw_test50 = pd.concat([df2_benign50, df2_generic50, df2_exploits50, df2_fuzzers50, df2_dos50, 
                             df2_reconnaissance50, df2_analysis50, df2_backdoor50, df2_shellcode50, df2_worms50])
# embaralha do dataframe 
df_unsw_test50 = shuffle(df_unsw_test50)
# reseta os indices
df_unsw_test50.reset_index(drop=True, inplace=True)
# verifica a dimensão
df_unsw_test50.shape

(1270018, 47)

In [31]:
#df_unsw_train50.tail()
df_unsw_test50.tail()

,sport,dsport,proto,state,dur,sbytes,dbytes,sttl,dttl,sloss,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
1270013,32153,39181,114,5,0.028830,2558,23470,31,29,7,...,7,10,3,3,5,1,1,2,Benign,0
1270014,34967,47344,120,2,0.000990,146,178,31,29,0,...,7,2,5,1,3,1,1,1,Benign,0
1270015,453,47344,120,6,0.000009,264,0,60,0,0,...,7,31,31,27,27,27,14,31,Benign,0
1270016,789,35849,114,5,0.019689,2766,28892,31,29,7,...,7,5,6,1,4,1,1,1,Benign,0
1270017,13154,51375,114,5,0.049067,424,8824,31,29,1,...,7,2,2,2,4,1,1,3,Benign,0

In [32]:
# exportando dataset unsw train50
df_unsw_train50.to_csv('/mnt/7830EC6930EC3034/UFU/email/df_unsw_train50.csv', index=False)

In [33]:
# exportando dataset unsw test50
df_unsw_test50.to_csv('/mnt/7830EC6930EC3034/UFU/email/df_unsw_test50.csv', index=False)