In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from yellowbrick.classifier import ConfusionMatrix

# Carregando dataset UNSW test pre-processamento MINIMO

In [2]:
df_unsw_test50 = pd.read_csv('/media/kelson/Maxtor/Trabalho/doutorado/artigo_preprocessamento/artigo/dataset_unsw/df_unsw_test50.csv', low_memory=False)

In [3]:
df_unsw_test50.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,35,42325,21,39962,114,5,0.039096,2974,31328,31,...,7,8,8,6,3,1,1,10,Benign,0
1,35,15576,22,63617,114,5,0.009790,424,8824,31,...,7,3,3,5,6,1,1,4,Benign,0
2,33,14173,27,12006,114,5,0.008764,2230,14740,31,...,7,2,3,1,3,1,1,1,Benign,0
3,38,33848,25,62606,114,5,1.036823,1580,10168,31,...,7,1,1,3,3,1,1,2,Benign,0
4,42,12229,21,12108,114,5,0.872706,2934,3740,31,...,1,1,1,2,3,1,1,4,Benign,0

# Divisão entre variáveis previsoras (x) e classe (y)

In [4]:
df_unsw_test50['Label_multiclass'] = df_unsw_test50['attack_cat']
df_unsw_test50['Label_binary'] = df_unsw_test50['Label']

In [5]:
df_unsw_test50.drop('attack_cat', axis = 1, inplace=True)
df_unsw_test50.drop('Label', axis = 1, inplace=True)

In [6]:
df_unsw_test50.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,Label_multiclass,Label_binary
0,35,42325,21,39962,114,5,0.039096,2974,31328,31,...,7,8,8,6,3,1,1,10,Benign,0
1,35,15576,22,63617,114,5,0.009790,424,8824,31,...,7,3,3,5,6,1,1,4,Benign,0
2,33,14173,27,12006,114,5,0.008764,2230,14740,31,...,7,2,3,1,3,1,1,1,Benign,0
3,38,33848,25,62606,114,5,1.036823,1580,10168,31,...,7,1,1,3,3,1,1,2,Benign,0
4,42,12229,21,12108,114,5,0.872706,2934,3740,31,...,1,1,1,2,3,1,1,4,Benign,0

In [7]:
# atribuição dos valores para X e y
X_test50 = df_unsw_test50.iloc[:,:47]
y_test50_multiclass = df_unsw_test50.Label_multiclass
y_test50_binary = df_unsw_test50.Label_binary
print('Dimensões para X: ', X_test50.shape)
print('Dimensões para y_multiclass: ', y_test50_multiclass.shape)
print('Dimensões para y_binary: ', y_test50_binary.shape)

Dimensões para X:  (1270018, 47)
Dimensões para y_multiclass:  (1270018,)
Dimensões para y_binary:  (1270018,)

In [8]:
X_test50

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_flw_http_mthd,is_ftp_login,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src__ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm
0,35,42325,21,39962,114,5,0.039096,2974,31328,31,...,7.0,3.0,7,8,8,6,3,1,1,10
1,35,15576,22,63617,114,5,0.009790,424,8824,31,...,7.0,3.0,7,3,3,5,6,1,1,4
2,33,14173,27,12006,114,5,0.008764,2230,14740,31,...,7.0,3.0,7,2,3,1,3,1,1,1
3,38,33848,25,62606,114,5,1.036823,1580,10168,31,...,1.0,3.0,7,1,1,3,3,1,1,2
4,42,12229,21,12108,114,5,0.872706,2934,3740,31,...,7.0,1.0,1,1,1,2,3,1,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270013,18,453,31,47344,120,6,0.000004,264,0,60,...,7.0,3.0,7,24,24,24,24,24,24,24
1270014,41,12097,8,47344,120,2,0.001040,146,178,31,...,7.0,3.0,7,4,4,5,6,3,1,3
1270015,37,41669,21,24852,114,5,0.057800,2854,27886,31,...,7.0,3.0,7,5,5,2,2,1,1,1
1270016,39,57171,9,47344,120,2,0.000973,146,178,31,...,7.0,3.0,7,1,1,2,1,1,1,1
1270017,14,453,29,47344,120,6,0.000003,264,0,60,...,7.0,3.0,7,40,40,40,40,40,22,40

In [9]:
y_test50_multiclass

0          Benign
1          Benign
2          Benign
3          Benign
4          Benign
            ...
1270013    Benign
1270014    Benign
1270015    Benign
1270016    Benign
1270017    Benign
Name: Label_multiclass, Length: 1270018, dtype: object

In [10]:
y_test50_binary

0          0
1          0
2          0
3          0
4          0
          ..
1270013    0
1270014    0
1270015    0
1270016    0
1270017    0
Name: Label_binary, Length: 1270018, dtype: int64

# Salvando as variáveis X_test50, y_test50_multiclass,  y_test50_binary em arquivo único

In [11]:
import pickle

In [12]:
with open('df_unsw_test50_no_preprocessing_labelencoder', mode = 'wb') as f:
    pickle.dump([X_test50, y_test50_multiclass, y_test50_binary], f)